//! Generated coverage of the codec (`IMPLEMENTATION.md` § 9).
//!
//! The unit tests next to the codec pin down cases a human thought of. These
//! cover the ones nobody would: every field at its extremes, every frame type
//! pointed at every payload, and payloads that are one flipped bit away from
//! valid. Both halves of the codec read bytes the peer chose, so the bar is not
//! "rejects bad input" but "never panics on any input" — `indexing_slicing` is
//! denied crate-wide, which makes an out-of-bounds panic unlikely rather than
//! impossible.
//!
//! This is the fuzzing story for the parser, run on stable as part of the normal
//! suite rather than as a `cargo-fuzz` target: the input space that matters is a
//! 4-byte header and a length-prefixed payload, which proptest reaches by
//! construction. A nightly `cargo-fuzz` target would buy coverage-guided search
//! over longer inputs and remains worth adding, but nothing here depends on it.

use nomux_proto::{
    ErrorCode, ExitKind, Frame, FrameType, HEADER_LEN, HELLO_AGENT_FORWARD, HELLO_REPAINT_CTRL_L,
    Hello, HelloOk, Linger, MAX_PAYLOAD, ProtoError, WinSize, decode_header,
};
use proptest::prelude::*;

/// Cap on generated `data` and `term` lengths.
///
/// The codec treats those fields as opaque tails, so the interesting behaviour is
/// all at 0, 1 and "more than the fixed prefix". Generating anything near
/// [`MAX_PAYLOAD`] would only slow the suite down.
const MAX_GENERATED_LEN: usize = 24;

/// Owned mirror of [`Frame`], whose `data`, `term` and `message` fields borrow.
///
/// A strategy yields values by value, so the generated bytes must outlive the frame
/// pointing at them. Every borrowed field in this protocol is either UTF-8 text or
/// opaque bytes, and no frame carries both, so one slot of each covers all five of
/// them — `Hello.term`, `Input.data`, `Output.data`, `Error.message` and
/// `AgentData.data`: the frame travels with an empty placeholder in the borrowed
/// field and [`OwnedFrame::frame`] hands back a copy pointing at the owned value
/// instead. A mirror enum would restate those five variants the compiler already
/// knows about, and would need a sixth the day a frame grows a borrowed field.
#[derive(Debug, Clone)]
struct OwnedFrame {
    /// The frame, with a placeholder wherever it borrows.
    frame: Frame<'static>,
    /// Backing store for a borrowed `term` or `message`.
    text: String,
    /// Backing store for a borrowed `data`.
    bytes: Vec<u8>,
}

impl OwnedFrame {
    /// Wraps a frame that borrows nothing.
    const fn copied(frame: Frame<'static>) -> Self {
        Self::with_text(frame, String::new())
    }

    /// Wraps a frame whose text field [`OwnedFrame::frame`] will point at `text`.
    const fn with_text(frame: Frame<'static>, text: String) -> Self {
        Self {
            frame,
            text,
            bytes: Vec::new(),
        }
    }

    /// Wraps a frame whose byte field [`OwnedFrame::frame`] will point at `bytes`.
    const fn with_bytes(frame: Frame<'static>, bytes: Vec<u8>) -> Self {
        Self {
            frame,
            text: String::new(),
            bytes,
        }
    }

    /// Lends a [`Frame`] borrowing from `self`.
    fn frame(&self) -> Frame<'_> {
        match self.frame {
            Frame::Hello(hello) => Frame::Hello(Hello {
                term: &self.text,
                ..hello
            }),
            Frame::Error { code, .. } => Frame::Error {
                code,
                message: &self.text,
            },
            Frame::Input { offset, .. } => Frame::Input {
                offset,
                data: &self.bytes,
            },
            Frame::Output { offset, .. } => Frame::Output {
                offset,
                data: &self.bytes,
            },
            Frame::AgentData { chan, .. } => Frame::AgentData {
                chan,
                data: &self.bytes,
            },
            borrows_nothing => borrows_nothing,
        }
    }
}

/// Strategy for terminal dimensions.
///
/// Unconstrained: the codec is not the layer that decides a 0x0 terminal is
/// nonsense, and a size it silently clamps would be a bug this must catch.
fn any_win() -> impl Strategy<Value = WinSize> {
    (any::<u16>(), any::<u16>(), any::<u16>(), any::<u16>()).prop_map(|(cols, rows, x, y)| {
        WinSize {
            cols,
            rows,
            xpixel: x,
            ypixel: y,
        }
    })
}

/// Strategy for bounded UTF-8 text.
///
/// Built from `char` rather than a regex so the length bound is in characters the
/// generator actually emits, and so surrogate-adjacent and multi-byte scalars turn
/// up rather than being filtered out by a pattern.
fn any_text() -> impl Strategy<Value = String> {
    prop::collection::vec(any::<char>(), 0..=MAX_GENERATED_LEN).prop_map(String::from_iter)
}

/// Strategy for a bounded opaque payload.
fn any_bytes() -> impl Strategy<Value = Vec<u8>> {
    prop::collection::vec(any::<u8>(), 0..=MAX_GENERATED_LEN)
}

/// Strategy for `Hello.flags`.
///
/// Restricted to the two defined bits, because the decoder refuses anything else
/// by design; undefined bits are covered by the mutation property instead.
fn any_hello_flags() -> impl Strategy<Value = u16> {
    (any::<bool>(), any::<bool>()).prop_map(|(agent, ctrl_l)| {
        u16::from(agent) * HELLO_AGENT_FORWARD + u16::from(ctrl_l) * HELLO_REPAINT_CTRL_L
    })
}

/// Strategy for every [`Frame`] variant with arbitrary field values.
fn any_frame() -> impl Strategy<Value = OwnedFrame> {
    // Driven from the `ALL` the discriminant lists generate, not from a hand-written
    // list of `Just`s: a value missing from such a list is simply never generated,
    // and nothing says so — the same hole on the generating side that `from_byte`
    // ending in `_ => None` used to leave on the parsing side.
    let linger = prop::sample::select(Linger::ALL.to_vec());
    let error_code = prop::sample::select(ErrorCode::ALL.to_vec());
    let exit_kind = prop::sample::select(ExitKind::ALL.to_vec());

    // `prop_oneof!` caps out at a limited number of arms, and the fixed-field
    // variants all collapse to one shape anyway, so they are built as a single
    // strategy of frames that borrow nothing.
    let copied = prop_oneof![
        (
            any::<u16>(),
            any::<u64>(),
            any::<u64>(),
            any_win(),
            any::<bool>(),
            linger,
            any::<bool>(),
        )
            .prop_map(
                |(protocol, resume_from, in_applied, win, gap, linger, agent)| {
                    Frame::HelloOk(HelloOk {
                        protocol,
                        resume_from,
                        in_applied,
                        win,
                        gap,
                        linger,
                        agent,
                    })
                }
            ),
        any::<u64>().prop_map(|applied_through| Frame::InputAck { applied_through }),
        any::<u64>().prop_map(|consumed_through| Frame::OutputAck { consumed_through }),
        any_win().prop_map(Frame::Resize),
        any::<u64>().prop_map(|new_base_offset| Frame::Gap { new_base_offset }),
        (any::<i32>(), exit_kind).prop_map(|(status, kind)| Frame::Exit { status, kind }),
        Just(Frame::Detach),
        any::<u64>().prop_map(|nonce| Frame::Ping { nonce }),
        any::<u64>().prop_map(|nonce| Frame::Pong { nonce }),
        any::<u32>().prop_map(|chan| Frame::AgentOpen { chan }),
        any::<u32>().prop_map(|chan| Frame::AgentClose { chan }),
    ];

    prop_oneof![
        copied.prop_map(OwnedFrame::copied),
        (
            any::<u16>(),
            any_hello_flags(),
            any::<u64>(),
            any::<u64>(),
            any_win(),
            any_text(),
        )
            .prop_map(|(protocol, flags, out_offset, in_offset, win, term)| {
                OwnedFrame::with_text(
                    Frame::Hello(Hello {
                        protocol,
                        flags,
                        out_offset,
                        in_offset,
                        win,
                        term: "",
                    }),
                    term,
                )
            }),
        (any::<u64>(), any_bytes()).prop_map(|(offset, data)| OwnedFrame::with_bytes(
            Frame::Input { offset, data: b"" },
            data
        )),
        (any::<u64>(), any_bytes()).prop_map(|(offset, data)| OwnedFrame::with_bytes(
            Frame::Output { offset, data: b"" },
            data
        )),
        (error_code, any_text()).prop_map(|(code, message)| OwnedFrame::with_text(
            Frame::Error { code, message: "" },
            message
        )),
        (any::<u32>(), any_bytes()).prop_map(|(chan, data)| OwnedFrame::with_bytes(
            Frame::AgentData { chan, data: b"" },
            data
        )),
    ]
}

/// Encodes `frame` and returns the bytes after the header, having checked that the
/// header describes what follows it.
///
/// Reports failures instead of panicking: the `allow-*-in-tests` settings in
/// `clippy.toml` cover `#[test]` bodies, not helpers beside them, and a shrunk
/// counterexample is more useful than a backtrace regardless.
fn encode_and_split(frame: Frame<'_>) -> Result<Vec<u8>, TestCaseError> {
    let mut buf = Vec::new();
    frame
        .encode(&mut buf)
        .map_err(|err| TestCaseError::fail(format!("encode refused {frame:?}: {err}")))?;

    let Some(header) = buf.first_chunk::<HEADER_LEN>() else {
        return Err(TestCaseError::fail("encode emitted no header"));
    };
    let header = decode_header(header)
        .map_err(|err| TestCaseError::fail(format!("own header rejected: {err}")))?;
    let payload = buf.split_off(HEADER_LEN);

    prop_assert_eq!(
        header.ty,
        frame.frame_type(),
        "header type disagrees with the frame it precedes"
    );
    prop_assert_eq!(
        header.len as usize,
        payload.len(),
        "declared length disagrees with the payload written"
    );
    Ok(payload)
}

/// Offers `payload` to every frame type and checks the invariant that must hold
/// for bytes from a hostile peer: not panicking, and — when the bytes are accepted
/// — being the *only* encoding of what they decoded to.
///
/// Canonicality is the sharper half. A decoder that accepts two spellings of one
/// frame lets a peer smuggle bytes past anything downstream that compares
/// encodings, and it is exactly what a hand-written test suite misses.
fn decode_as_every_type(payload: &[u8]) -> Result<(), TestCaseError> {
    // Every type rather than a sampled few: a decode apiece is far cheaper than the
    // shrinking proptest would otherwise need to find the one type that mishandles a
    // given payload. [`FrameType::ALL`] is generated from the discriminant list, so a
    // new frame type joins this sweep without anyone having to remember it.
    for ty in FrameType::ALL {
        let Ok(frame) = Frame::decode(ty, payload) else {
            continue;
        };
        prop_assert_eq!(
            frame.frame_type(),
            ty,
            "decoded as a different type than it was asked for"
        );
        let re_encoded = encode_and_split(frame)?;
        prop_assert_eq!(
            re_encoded.as_slice(),
            payload,
            "accepted a non-canonical encoding of {:?}",
            frame
        );
    }
    Ok(())
}

proptest! {
    // Eight times proptest's default. The codec is a few hundred branches over
    // buffers this suite keeps tiny, so the whole file still runs in well under a
    // second — and a rejection sampler looking for, say, a valid `ErrorCode` in two
    // random bytes needs the cases far more than it needs the time back.
    #![proptest_config(ProptestConfig { cases: 2048, ..ProptestConfig::default() })]

    /// Encoding then decoding is the identity, for every variant over its whole
    /// field domain. The hand-written cases fix one plausible value per field,
    /// which cannot catch a field that is only wrong at its extremes — a `u64`
    /// offset truncated to 32 bits, or a signed exit status losing its sign.
    #[test]
    fn every_frame_round_trips(owned in any_frame()) {
        let frame = owned.frame();
        let payload = encode_and_split(frame)?;
        let decoded = Frame::decode(frame.frame_type(), &payload)
            .map_err(|err| TestCaseError::fail(format!("own encoding rejected: {err}")))?;
        prop_assert_eq!(decoded, frame, "round trip changed the frame");
    }

    /// `decode_header` is total over its input: it reads four bytes off the wire
    /// before anything has been validated, so there is no input it may refuse to
    /// return from. It must also promise exactly what the rest of the daemon
    /// relies on — a known type, and a length that bounds the next allocation.
    #[test]
    fn header_decode_is_total(bytes in any::<[u8; HEADER_LEN]>()) {
        let [ty, a, b, c] = bytes;
        let len = u32::from_be_bytes([0, a, b, c]);
        match decode_header(&bytes) {
            Ok(header) => {
                prop_assert_eq!(FrameType::from_byte(ty), Some(header.ty), "invented a type");
                prop_assert_eq!(header.len, len, "length is not the low 24 bits");
                prop_assert!(header.len <= MAX_PAYLOAD, "accepted an unbounded allocation");
            }
            Err(ProtoError::UnknownFrameType(reported)) => {
                prop_assert_eq!(reported, ty, "reported a byte it did not read");
                prop_assert!(FrameType::from_byte(ty).is_none(), "refused a known type");
            }
            Err(ProtoError::PayloadTooLarge(reported)) => {
                prop_assert_eq!(reported, len, "reported a length it did not read");
                prop_assert!(len > MAX_PAYLOAD, "refused a length within the cap");
            }
            Err(other) => {
                return Err(TestCaseError::fail(format!(
                    "header decode cannot produce {other:?}"
                )));
            }
        }
    }

    /// `Frame::decode` is total over arbitrary payloads for every frame type.
    ///
    /// The type byte and the payload arrive from the same untrusted stream and are
    /// not checked against each other, so a peer can point any type at any bytes.
    #[test]
    fn payload_decode_is_total(payload in prop::collection::vec(any::<u8>(), 0..=40)) {
        decode_as_every_type(&payload)?;
    }

    /// The same, on payloads one byte away from valid.
    ///
    /// Uniform random bytes almost never reach the code past a length prefix or an
    /// enum discriminant; a real encoding with one byte flipped or amputated does,
    /// and lands on the boundaries — a `term_len` larger than what follows, a
    /// reserved flag bit, a truncated final field.
    #[test]
    fn mutated_encodings_decode_without_panicking(
        owned in any_frame(),
        position in any::<u16>(),
        flip in 1u8..=u8::MAX,
        truncate in any::<bool>(),
    ) {
        let mut payload = encode_and_split(owned.frame())?;
        let position = usize::from(position).checked_rem(payload.len()).unwrap_or(0);
        if let Some(byte) = payload.get_mut(position) {
            *byte ^= flip;
        }
        if truncate {
            payload.pop();
        }
        decode_as_every_type(&payload)?;
    }
}
