//! Generated coverage of the codec (`IMPLEMENTATION.md` § 9).
//!
//! Every field at its extremes, every frame type pointed at every payload, and
//! payloads one flipped bit away from valid. The codec reads bytes the peer chose, so
//! the bar is not "rejects bad input" but "never panics on any input" —
//! `indexing_slicing` is denied crate-wide, which makes an out-of-bounds panic unlikely
//! rather than impossible.
//!
//! This is the fuzzing story for the parser, run on stable as part of the normal suite
//! rather than as a `cargo-fuzz` target: the input space that matters is a 4-byte
//! header and a length-prefixed payload, which proptest reaches by construction. What
//! it cannot see is the wire itself — it generates frames and compares frames, so the
//! byte layout is `wire.rs`'s job.

use nomux_proto::{
    ErrorCode, ExitKind, Frame, FrameType, HEADER_LEN, Hello, HelloOk, Linger, MAX_PAYLOAD,
    ProtoError, WinSize, decode_header,
};
use proptest::prelude::*;
use proptest::strategy::ValueTree;
use proptest::test_runner::TestRunner;
use std::collections::HashSet;

/// Cap on generated `data` and `term` lengths.
///
/// The codec treats those fields as opaque tails, so the interesting behaviour is all
/// at 0, 1 and "more than the fixed prefix"; anything near [`MAX_PAYLOAD`] would only
/// slow the suite down.
const MAX_GENERATED_LEN: usize = 24;

/// Owned mirror of [`Frame`], whose `data`, `term` and `message` fields borrow.
///
/// A strategy yields values by value, so the generated bytes must outlive the frame
/// pointing at them. No frame borrows both text and bytes, so one slot of each covers
/// all five borrowed fields: the frame travels with an empty placeholder and
/// [`OwnedFrame::frame`] hands back a copy pointing at the owned value.
#[derive(Debug, Clone)]
struct OwnedFrame {
    /// The frame, with a placeholder wherever it borrows.
    frame: Frame<'static>,
    /// Backing store for a borrowed `term` or `message`.
    text: String,
    /// Backing store for a borrowed `data`.
    bytes: Vec<u8>,
}

impl OwnedFrame {
    /// Wraps a frame that borrows nothing.
    const fn copied(frame: Frame<'static>) -> Self {
        Self::with_text(frame, String::new())
    }

    /// Wraps a frame whose text field [`OwnedFrame::frame`] will point at `text`.
    const fn with_text(frame: Frame<'static>, text: String) -> Self {
        Self {
            frame,
            text,
            bytes: Vec::new(),
        }
    }

    /// Wraps a frame whose byte field [`OwnedFrame::frame`] will point at `bytes`.
    const fn with_bytes(frame: Frame<'static>, bytes: Vec<u8>) -> Self {
        Self {
            frame,
            text: String::new(),
            bytes,
        }
    }

    /// Lends a [`Frame`] borrowing from `self`.
    fn frame(&self) -> Frame<'_> {
        match self.frame {
            Frame::Hello(hello) => Frame::Hello(Hello {
                term: &self.text,
                ..hello
            }),
            Frame::Error { code, .. } => Frame::Error {
                code,
                message: &self.text,
            },
            Frame::Input { offset, .. } => Frame::Input {
                offset,
                data: &self.bytes,
            },
            Frame::Output { offset, .. } => Frame::Output {
                offset,
                data: &self.bytes,
            },
            Frame::AgentData { .. } => Frame::AgentData { data: &self.bytes },
            borrows_nothing => borrows_nothing,
        }
    }
}

/// Strategy for terminal dimensions, unconstrained: the codec is not the layer that
/// decides a 0x0 terminal is nonsense, and a size it silently clamped would be a bug
/// this must catch.
fn any_win() -> impl Strategy<Value = WinSize> {
    (any::<u16>(), any::<u16>(), any::<u16>(), any::<u16>()).prop_map(|(cols, rows, x, y)| {
        WinSize {
            cols,
            rows,
            xpixel: x,
            ypixel: y,
        }
    })
}

/// Strategy for bounded UTF-8 text.
///
/// Built from `char` rather than a regex, so the bound is in characters the generator
/// emits and multi-byte scalars turn up rather than being filtered out by a pattern.
fn any_text() -> impl Strategy<Value = String> {
    prop::collection::vec(any::<char>(), 0..=MAX_GENERATED_LEN).prop_map(String::from_iter)
}

/// Strategy for `Hello.term`: [`any_text`] minus U+0000, which the codec refuses there
/// by design — valid UTF-8 that `execve` will not take, so not a well-formed frame.
/// This generator's job is the frames that encode; the refusal is covered by the
/// mutation property below and by a unit test beside the check.
///
/// Mapped rather than filtered because `any::<char>()` deliberately samples U+0000, so
/// a filter would spend proptest's reject budget on a case trivially rewritten.
fn any_term() -> impl Strategy<Value = String> {
    prop::collection::vec(
        any::<char>().prop_map(|c| if c == '\0' { '\u{fffd}' } else { c }),
        0..=MAX_GENERATED_LEN,
    )
    .prop_map(String::from_iter)
}

/// Strategy for a bounded opaque payload.
fn any_bytes() -> impl Strategy<Value = Vec<u8>> {
    prop::collection::vec(any::<u8>(), 0..=MAX_GENERATED_LEN)
}

/// Strategy for every [`Frame`] variant with arbitrary field values.
fn any_frame() -> impl Strategy<Value = OwnedFrame> {
    // From each set's `ALL`, so a value added to the protocol is generated without
    // anyone remembering to add it here.
    let linger = prop::sample::select(Linger::ALL.to_vec());
    let error_code = prop::sample::select(ErrorCode::ALL.to_vec());
    let exit_kind = prop::sample::select(ExitKind::ALL.to_vec());

    // The variants that borrow nothing, in one group, `prop_oneof!` costing an arm
    // apiece. The five payload-less ones share the last arm, having no field to sample
    // between them; [`every_frame_type_is_generated`] checks that none went missing.
    let copied = prop_oneof![
        (any::<u64>(), any::<u64>(), linger, any::<bool>()).prop_map(
            |(resume_from, in_applied, linger, agent)| {
                Frame::HelloOk(HelloOk {
                    resume_from,
                    in_applied,
                    linger,
                    agent,
                })
            }
        ),
        any::<u64>().prop_map(|applied_through| Frame::InputAck { applied_through }),
        any_win().prop_map(Frame::Resize),
        any::<u64>().prop_map(|new_base_offset| Frame::Gap { new_base_offset }),
        (any::<i32>(), exit_kind, any::<u32>()).prop_map(|(status, kind, since_exit_secs)| {
            Frame::Exit {
                status,
                kind,
                since_exit_secs,
            }
        }),
        prop::sample::select(vec![
            Frame::Detach,
            Frame::Ping,
            Frame::Pong,
            Frame::AgentOpen,
            Frame::AgentClose,
        ]),
    ];

    prop_oneof![
        copied.prop_map(OwnedFrame::copied),
        (
            any::<u16>(),
            any::<bool>(),
            any::<bool>(),
            any::<u64>(),
            any_win(),
            any_term(),
        )
            .prop_map(
                |(protocol, agent_forward, repaint_ctrl_l, out_offset, win, term)| {
                    OwnedFrame::with_text(
                        Frame::Hello(Hello {
                            protocol,
                            agent_forward,
                            repaint_ctrl_l,
                            out_offset,
                            win,
                            term: "",
                        }),
                        term,
                    )
                },
            ),
        (any::<u64>(), any_bytes()).prop_map(|(offset, data)| OwnedFrame::with_bytes(
            Frame::Input { offset, data: b"" },
            data
        )),
        (any::<u64>(), any_bytes()).prop_map(|(offset, data)| OwnedFrame::with_bytes(
            Frame::Output { offset, data: b"" },
            data
        )),
        (error_code, any_text()).prop_map(|(code, message)| OwnedFrame::with_text(
            Frame::Error { code, message: "" },
            message
        )),
        any_bytes().prop_map(|data| OwnedFrame::with_bytes(Frame::AgentData { data: b"" }, data)),
    ]
}

/// Encodes `frame` and returns the bytes after the header, having checked that the
/// header describes what follows it.
///
/// Reports failures instead of panicking: `clippy.toml`'s `allow-*-in-tests` covers
/// `#[test]` bodies, not helpers beside them, and a shrunk counterexample beats a
/// backtrace regardless.
fn encode_and_split(frame: Frame<'_>) -> Result<Vec<u8>, TestCaseError> {
    let mut buf = Vec::new();
    frame
        .encode(&mut buf)
        .map_err(|err| TestCaseError::fail(format!("encode refused {frame:?}: {err}")))?;

    let Some(header) = buf.first_chunk::<HEADER_LEN>() else {
        return Err(TestCaseError::fail("encode emitted no header"));
    };
    let header = decode_header(header)
        .map_err(|err| TestCaseError::fail(format!("own header rejected: {err}")))?;
    let payload = buf.split_off(HEADER_LEN);

    prop_assert_eq!(
        header.ty,
        frame.frame_type(),
        "header type disagrees with the frame it precedes"
    );
    prop_assert_eq!(
        header.len as usize,
        payload.len(),
        "declared length disagrees with the payload written"
    );
    Ok(payload)
}

/// [`any_frame`] generates every frame type.
///
/// Its `prop_oneof!` arms are the one list here still written by hand, and a variant
/// missing from them is never round-tripped. The sweeps below take arbitrary payloads
/// to every type and so reach a new variant's decoder, but never its field domain.
///
/// Deterministic rather than a `proptest!` case: this asserts coverage of the generator
/// rather than a property of the codec, and coverage that passes by luck is worse than
/// none.
#[test]
fn every_frame_type_is_generated() {
    let mut runner = TestRunner::deterministic();
    let strategy = any_frame();
    let mut seen = HashSet::new();
    for _ in 0..4096 {
        let owned = strategy.new_tree(&mut runner).unwrap().current();
        seen.insert(owned.frame().frame_type());
    }

    for ty in FrameType::ALL {
        assert!(seen.contains(&ty), "any_frame never generates {ty:?}");
    }
}

/// Offers `payload` to every frame type and checks what must hold for bytes from a
/// hostile peer: not panicking, and — when accepted — being the *only* encoding of what
/// they decoded to. A decoder that takes two spellings of one frame lets a peer smuggle
/// bytes past anything downstream that compares encodings.
fn decode_as_every_type(payload: &[u8]) -> Result<(), TestCaseError> {
    // Every type rather than a sampled few: a decode apiece is far cheaper than the
    // shrinking it would otherwise take to find the one type that mishandles a payload.
    // [`FrameType::ALL`] comes from the discriminant list, so a new type joins by itself.
    for ty in FrameType::ALL {
        let Ok(frame) = Frame::decode(ty, payload) else {
            continue;
        };
        prop_assert_eq!(
            frame.frame_type(),
            ty,
            "decoded as a different type than it was asked for"
        );
        let re_encoded = encode_and_split(frame)?;
        prop_assert_eq!(
            re_encoded.as_slice(),
            payload,
            "accepted a non-canonical encoding of {:?}",
            frame
        );
    }
    Ok(())
}

proptest! {
    // Eight times proptest's default: the codec is a few hundred branches over tiny
    // buffers, so the file still runs in well under a second, and finding a valid
    // `ErrorCode` in two random bytes needs the cases more than it needs the time back.
    #![proptest_config(ProptestConfig { cases: 2048, ..ProptestConfig::default() })]

    /// Encoding then decoding is the identity, for every variant over its whole field
    /// domain — including the extremes a fixed value per field cannot reach, such as a
    /// `u64` offset truncated to 32 bits or a signed exit status losing its sign.
    #[test]
    fn every_frame_round_trips(owned in any_frame()) {
        let frame = owned.frame();
        let payload = encode_and_split(frame)?;
        let decoded = Frame::decode(frame.frame_type(), &payload)
            .map_err(|err| TestCaseError::fail(format!("own encoding rejected: {err}")))?;
        prop_assert_eq!(decoded, frame, "round trip changed the frame");
    }

    /// `decode_header` is total over its input: it reads four bytes off the wire before
    /// anything has been validated, so there is no input it may refuse to return from.
    /// It must also promise what the rest of the daemon relies on — a known type, and a
    /// length that bounds the next allocation.
    #[test]
    fn header_decode_is_total(bytes in any::<[u8; HEADER_LEN]>()) {
        let [ty, a, b, c] = bytes;
        let len = u32::from_be_bytes([0, a, b, c]);
        match decode_header(&bytes) {
            Ok(header) => {
                prop_assert_eq!(FrameType::from_byte(ty), Some(header.ty), "invented a type");
                prop_assert_eq!(header.len, len, "length is not the low 24 bits");
                prop_assert!(header.len <= MAX_PAYLOAD, "accepted an unbounded allocation");
            }
            Err(ProtoError::UnknownFrameType(reported)) => {
                prop_assert_eq!(reported, ty, "reported a byte it did not read");
                prop_assert!(FrameType::from_byte(ty).is_none(), "refused a known type");
            }
            Err(ProtoError::PayloadTooLarge(reported)) => {
                prop_assert_eq!(reported, len, "reported a length it did not read");
                prop_assert!(len > MAX_PAYLOAD, "refused a length within the cap");
            }
            Err(other) => {
                return Err(TestCaseError::fail(format!(
                    "header decode cannot produce {other:?}"
                )));
            }
        }
    }

    /// `Frame::decode` is total over arbitrary payloads for every frame type.
    ///
    /// The type byte and the payload arrive from the same untrusted stream and are
    /// not checked against each other, so a peer can point any type at any bytes.
    #[test]
    fn payload_decode_is_total(payload in prop::collection::vec(any::<u8>(), 0..=40)) {
        decode_as_every_type(&payload)?;
    }

    /// A `Hello` whose declared `term_len` runs past the bytes behind it.
    ///
    /// The one length prefix on this wire. The sweeps above reach its boundary only on
    /// the rare payload already shaped like a `Hello`, and accept any refusal there;
    /// this reaches it every time and pins which refusal.
    #[test]
    fn a_hello_that_overstates_its_term_length_is_truncated(
        term in any_bytes(),
        beyond in 1u16..=u16::MAX,
    ) {
        // The fixed prefix § 2.2 gives `Hello` — protocol, flags, out_offset,
        // winsize — all zero, which is a shape the decoder accepts.
        let mut payload = vec![0u8; 19];
        let declared = u16::try_from(term.len()).unwrap_or(u16::MAX).saturating_add(beyond);
        payload.extend_from_slice(&declared.to_be_bytes());
        payload.extend_from_slice(&term);
        prop_assert_eq!(
            Frame::decode(FrameType::Hello, &payload),
            Err(ProtoError::Truncated),
            "declared {} with {} bytes behind it",
            declared,
            term.len()
        );
        decode_as_every_type(&payload)?;
    }

    /// The same, on payloads one byte away from valid.
    ///
    /// Uniform random bytes almost never reach the code past a length prefix or an enum
    /// discriminant; a real encoding with one byte flipped or amputated does, and lands
    /// on the boundaries — a `term_len` larger than what follows, a reserved flag bit,
    /// a truncated final field.
    #[test]
    fn mutated_encodings_decode_without_panicking(
        owned in any_frame(),
        position in any::<u16>(),
        flip in 1u8..=u8::MAX,
        truncate in any::<bool>(),
    ) {
        let mut payload = encode_and_split(owned.frame())?;
        let position = usize::from(position).checked_rem(payload.len()).unwrap_or(0);
        if let Some(byte) = payload.get_mut(position) {
            *byte ^= flip;
        }
        if truncate {
            payload.pop();
        }
        decode_as_every_type(&payload)?;
    }
}
